### PR TITLE
Fix for issue 136 - Bounding Box was initialized with wrong values.

### PR DESCRIPTION
**Pull request by Josephblt**
Fix for issue 136 - Bounding Box was initialized with wrong values.

### CODE REVIEW

**Comment by romartin** [comment]
Hey @Josephblt 
It seems this fix is not the root issue for this, as I'm still able to reproduce it :(

So after playing a bit with the wires resize... I got this:
lienzo-136

This error is even difficult to reproduce, it's still not clear for me which are the right steps for reproducing it always and being able to debug it :(

**Review by romartin — CHANGES_REQUESTED** [review]
Still not fixed

**Comment by Josephblt** [comment]
I figured out how to simulate the bug. If you scale it to a really small value (put the handles over each other) the problem happens.

**Comment by romartin** [comment]
ohh good point @Josephblt ! :)

**Review by SprocketNYC — COMMENTED** [review]
already fixed

**Comment by romartin** [comment]
hey @SprocketNYC ,
mmm not sure if that is already fixed, I don't think so. Did you fixed something? AFAIK @Josephblt  is still working on this.
Thanks!!

**Pull request closed without merging**
