### PR TITLE
[JBPM-6045] Shapes are resized properly under a zoom mediator

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Comment by romartin** [comment]
Hey @Christopher-Chianelli ,

Tested this commit in Stunner, and the resize CPS are still not working fine (after zoom applied into the canvas). Works better than before but still some bug there... See screenshot:

resize-and-zoom-issues

**Comment by Christopher-Chianelli** [comment]
@romartin The issue appears to occur when the shape is resized too small; as for the reason, I don't know. I think it occurs when the shape is resized to `newshape.width <= shape.width/2` or `newshape.height <= shape.height/2`. Resizing the shape to be larger doesn't have this issue.

**Comment by Christopher-Chianelli** [comment]
@romartin The issue should be completely fixed. I have removed the old logic and replaced it with something simpler. Is there any lienzo app I can use to test this on other shapes (like triangle, circles, etc)? I want to make sure it doesn't break anything for the other shapes, since this basically remove control point logic.

**Comment by romartin** [comment]
Great @Christopher-Chianelli , tested and all good now!! Good job!

@SprocketNYC Dean this is ready for you to review and merge. Thanks!!!!

**Pull request merged**
