### PR TITLE
Improved Wires Support for Groups

### PR DESCRIPTION
**Pull request by mdproctor**
-Added Shadow Model so that nested containers can be supported, with an understanding of Connectors.
-Connectors now work across nested groups.
-Distribution and Alignment not works across nested groups.
-Drag and Drop now works between groups

### CODE REVIEW

**Comment by helmutprovost** [comment]
Hi Dean,

the example in http://www.lienzo-core.com/lienzo-ks/#ALIGN_DISTRIBUTE does no longer work.
Maybe it has to do something with these changes?

**Comment by SprocketNYC** [comment]
I'll notify Mark Proctor.... this is his code and many things have changed. I think we still consider anything in the wires package "beta"

**Comment by helmutprovost** [comment]
Allright, I noticed https://github.com/ahome-it/lienzo-core/pull/96# as possible fix, but I guess  http://www.lienzo-core.com/lienzo-ks/ is not using the latest jar jet.

**Comment by SprocketNYC** [comment]
Fixed

https://plus.google.com/+DeanJonesNYC/posts/9TCBowhQphB

**Pull request merged**
