### PR TITLE
Fix to make straight lines possible.

### PR DESCRIPTION
**Pull request by Josephblt**
Fix to make straight lines possible. @romartin.

### CODE REVIEW

**Comment by romartin** [comment]
Do NOT merge yet please - needs review

**Comment by romartin** [comment]
Hey @Josephblt ,
Tested and works fine, but on the other hand I think you're updating here the CPs for the OrthogonalPolyline, instead of changing the line drawing between CPs, as @mdproctor  recommended. Isn't it? Can pleae @mdproctor confirm?
PS: Probably the fix now it's just doing the `points.copy()` before your `correctBreakDistance`? (I mean in the `parse` method)

**Comment by romartin** [comment]
Yes @Josephblt , you're in fact changing the CPs of the line, which can cause trouble at some points...  not sure if you're around, anyway don't worry lemme try to fix this and create a PR for it now.

**Comment by SprocketNYC** [comment]
No merge yet, right?

**Comment by Josephblt** [comment]
Hey Roger. The points collection is cloned inside the correctBreakDistance
method to avoid changing Control Points position.

Em 23 de set de 2017 17:32, "Roger Martínez" <notifications@github.com>
escreveu:

**Comment by Josephblt** [comment]
I'll be home in about an hour. To try and fix this.

Em 23 de set de 2017 17:37, "Wagner Scholl Lemos" <josephblt@gmail.com>
escreveu:

**Comment by romartin** [comment]
ohhh @Josephblt sorry, yes you're doing it inside the method. In fact you're cloning the points twice at this point, you can just do it once at the begging of the `parse` method... but for me that's fine for now... we urgently need this fix in and a release! So please just provide a fix for this once possible next week and we can introduce it on next release, if you agree guys!

@SprocketNYC yeah for me all good!, can be merged if you agree too! 
@SprocketNYC  BTW please we need a release with last fixes... just preparing a summary mail, will send you in a bit. Really thanks!

Thanks guys!!

**Review by romartin — APPROVED** [review]
Thanks @Josephblt ! 
@SprocketNYC all good for me now, once you're happy too, ready to merge. Thx!

**Pull request merged**
