### PR TITLE
Issue #121, Issue #140

### PR DESCRIPTION
**Pull request by Josephblt**
Min Max Constraints Support - Issue #121
Round Corners Support - Issue #140. This fixes only part of the problem.

### CODE REVIEW

**Comment by romartin** [comment]
Hey @Josephblt 
Thanks for this, anyway still missing 2 things:

- Please change the commit message to reference the right ticket number (I think 121 is not the right one..). So just updating the commit message and force pushing again is fine.

- While dragging the resize CP, the shape size is being "constrained", that's working fine, but the concrete CP that is being drag, is still being located as the drag mouse location... I would expect forcing the location for the concrete CP as well, once it gets to its min/max, WDYT? 

See issue:
resize-constraints-issue

We're actually doing the same for shape docking - once a shape is being docked, while dragging it, it's located at the dock location although you keep moving the mouse ...

**Review by romartin — CHANGES_REQUESTED** [review]
Requested changes. See message above.

**Comment by Josephblt** [comment]
Yeah sure. Will work on those changes now.

2017-10-23 15:12 GMT-02:00 Roger Martínez <notifications@github.com>:

**Comment by romartin** [comment]
@Josephblt I think the best option is just setting a drag constraint enforcer for each of the resize CPs, and apply the right adjust once getting to the min/max values, if makes sense.

**Pull request closed without merging**
