### PR TITLE
JBPM-5452: Case Modeller

### PR DESCRIPTION
**Pull request by manstis**
This PR fixes method usage reported by romartin

@romartin Could you please check I've not messed up this time!?!

@SprocketNYC Hi Dean, please don't merge until Roger's had a chance to check I've not messed up.

@romartin @SprocketNYC What's the process with lienzo PRs then? Should I be updating version numbers too?

### CODE REVIEW

**Comment by romartin** [comment]
Hey @manstis @SprocketNYC , will try to summarize:

- @manstis this fix is good for me, but realized that lienzo-tests have to updated, tests are not passing since the commit for the CM stuff. You can just mock the layout handler and make tests pass or add some testing logic for it, up to you Mike! Thanks!

- @SprocketNYC I see different errors lemme know your thoughts Dean
:
1. Lienzo-core should be updated to 280-SNAPSHOT - currently the `279-RELEASE` on maven central does not have @manstis  changes, but building master's btanch locally, as pom and gradle still points to `2.0.279-RELEASE,` produces a different artifact, as Michael's commits are included

2. Lienzo-tests and lienzo-ks are updaetd with my latest commits but they depend and are on release `2.0.278` yet, so not sure what I'm really buildin now... 

@manstis @SprocketNYC I would say to wait for Michael to fix  lienzo-tests and then create a new 280-RELEASE for all lienzo-core, lienzo-tests and lienzo-ks ( with Mike's commit included as well ). Once done moving all three modules to a SNAPSHOT versions on master/2.0 branches. Agree guys? ( Probably I'm wrong.. i'm getting confuxed with artifacts and versions and all this stuff since latest release :( )

Thanks in advance!

**Comment by manstis** [comment]
@romartin 

"@manstis @SprocketNYC I would say to wait for Michael to fix lienzo-tests and then create a new 280-RELEASE for all lienzo-core, lienzo-tests and lienzo-ks ( with Mike's commit included as well ). Once done moving all three modules to a SNAPSHOT versions on master/2.0 branches. Agree guys?"

I think this makes sense to get things re-aligned.

**Comment by romartin** [comment]
Hey @manstis , @SprocketNYC , @mdproctor 

At this point we have a de-synchronization between lienzo core/tests/ks artifacts. @SprocketNYC could you please:
- merge [this](https://github.com/ahome-it/lienzo-tests/pull/5)  PR from @manstis 
- Once done, we should need a new release that includes latest Michael's stuff and fixes the GAVs. Do you want me to provide a PR for this? np for me! ( not sure if this need a PR or it's just some release process.. )

Thanks!!

**Comment by romartin** [comment]
@SprocketNYC so AFAIK (lemme know if I'm wrong)  the result should something as
- lienzo-core 2.0.280-RELEASE ( with @masntis stuff )
- lienzo-core master branch on 2.0.281-SNAPSHOT
- lienzo-rests 1.0.0-RC4  ( with @masntis stuff ) - depends on lienzo-core 2.0.280-RELEASE
- lienzo-tests master branch on 1.0.0-SNAPSHOT?? ( Not sure how to deal with RCs)
- same for lienzo-ks...

**Comment by manstis** [comment]
@romartin I think the following is more correct.

- lienzo-core 2.0 branch would be on 2.0.281-SNAPSHOT **not** master

**Comment by romartin** [comment]
@manstis @SprocketNYC  oh yes sorry, I mean the 2.0 branch instread of the master one :)

**Pull request merged**
